### ISSUE TITLE
stock_availables resource doesn't update

### ISSUE THREAD

**Issue by AlgirdasM** [Silentscripter/laravel-prestashop-webservice#19]
Hello,
stock_availables resource doesn't update.
Submiting code.

```
Route::get('/updatestock', function () {

	$xmlSchema=Prestashop::getSchema('stock_availables');
        $data = [
		'quantity' => '60'
	];

	$putXml=Prestashop::fillSchema($xmlSchema,$data,false);

	$opt['resource'] = 'stock_availables';
	$opt['id'] = '53'; // we get stock id from prestashop webservice
	$opt['putXml'] = $putXml->asXml();

	$xml=Prestashop::edit($opt);
});
```

```
array:3 [▼
  "resource" => "stock_availables"
  "id" => "53"
  "putXml" => """
    <?xml version="1.0" encoding="UTF-8"?>\n
    <prestashop xmlns:xlink="http://www.w3.org/1999/xlink">\n
    <stock_available>\n
    \t<id/>\n
    \t<id_product/>\n
    \t<id_product_attribute/>\n
    \t<id_shop/>\n
    \t<id_shop_group/>\n
    \t<quantity>60</quantity>\n
    \t<depends_on_stock/>\n
    \t<out_of_stock/>\n
    </stock_available>\n
    </prestashop>\n
    """
]
```

**Comment by Silentscripter** [comment]
Hi man, you are not posting the server response but as far as I see you've misused the stock_availables resource.
When youneed to update an existing resource you must not get the schema of the resource but rather get the resource itself with the specified ID like this `$resource = Prestashop::get(['resource' => 'stock_availables', 'id' => '53']);`

The you can update this resource with `fillSchema` method and then upload with `edit`. This is needed because you would otherwise miss to resend important information already present in the resource (in this case as you can see from the request you posted you are missing the id_product, id_product_attribute and the id_shop which are necessary for correctly linking the stock_available record to the product itself).
