### ISSUE TITLE
HTTP 302

### ISSUE THREAD

**Issue by SaeedDev94** [Silentscripter/laravel-prestashop-webservice#9]
Hi, i'm receiving HTTP 302 code, why? :(

```
Whoops, looks like something went wrong.

1/1
PrestaShopWebserviceException in PSWebServiceLibrary.php line 96:
This call to PrestaShop Web Services returned an unexpected HTTP status of:302
in PSWebServiceLibrary.php line 96
at PrestaShopWebservice->checkStatusCode(302) in PSWebServiceLibrary.php line 297
...
```

**Comment by Silentscripter** [comment]
Hi, this problem is not related to the library. Status code 302 means there's a redirection from the server to another location. The probable cause is a redirect due to http to https redirect settings or maybe prestahsop redirecting to www.domain from domain. You should look in prestashop seo & url configuration and verify the prestashop HOST you added to your environment file

**Comment by SaeedDev94** [comment]
thanks, problem solved ...

**Comment by PrajapatiDhara1510** [comment]
I am using external IP so I have changed Prestashop host to external IP. Now when I call API it shows me 
`This call to PrestaShop Web Services returned an unexpected HTTP status of: 302`

at the time API call I am using private IP. is there anything wrong?

**Comment by PrajapatiDhara1510** [comment]
I have solved this issue by this way if it helps anyone in same scenario:

Set shop URL ->
Shop domain: external IP added
SSL domain: private IP added

This way API will works.
